# Generated by Django 4.0.4 on 2022-05-27 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_score_remove_message_room_delete_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['typing_speed']},
        ),
        migrations.RenameField(
            model_name='score',
            old_name='typingspeed',
            new_name='typing_speed',
        ),
        migrations.RemoveField(
            model_name='score',
            name='created',
        ),
    ]
