# Generated by Django 4.0.4 on 2022-06-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_score_options_alter_score_accuracy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
