# Generated by Django 4.0.4 on 2022-06-08 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_message_user_delete_topic_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
